# Generated by Django 5.1.2 on 2025-01-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='pasw',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='signup',
            name='user',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
